route:
  group_by: ['instance','alertname']
  group_wait: 5m
  group_interval: 1h
  repeat_interval: 24h
  receiver: "tg_engdb"

  routes:
    - receiver: tg_engdb
        
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance'] 
    
receivers:
  - name: tg_engdb
    telegram_configs:
    - api_url: https://api.telegram.org
      bot_token: '8157382379:AAGf0bxhk3vSgKAEvQY_hu6xPtjm-1jKhtI'
      chat_id: 632306300
      message: '{{ template "telegram.not_default.message" . }}'

templates:
- '/etc/alertmanager/message_template.tmpl'
